theme: "hugo-theme-novela"
baseURL: "https://rainadoshi-portfolio.netlify.app/"
languageCode: "en-us"
title: "Raina Doshi"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "https://twitter.com/rainadoshi"
  github: "https://github.com/rainadoshi6"
  instagram: "https://instagram.com/rainadoshi98"
  linkedin: "https://www.linkedin.com/in/rainadoshi6/"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: Raina Doshi
