theme: "hugo-theme-novela"
baseURL: "https://rainadoshi-portfolio.netlify.app/"
languageCode: "en-us"
title: "Raina Doshi"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
